#pragma once

#include "Paths/Color.hpp"
#include "Paths/Common.hpp"

namespace Paths {

struct Material {
    Real m_reflectance {}; // 1 means perfect mirror
    Real m_ior {};         // index of refraction

    Color m_albedo {};
    Color m_emittance {};
};

enum class EMaterialPreset {
    Acetone,
    Actinolite,
    Agalmatoite,
    Agate,
    AgateMoss,
    Air,
    Alcohol,
    Alexandrite,
    Aluminum,
    Amber,
    Amblygonite,
    Amethyst,
    Anatase,
    Andalusite,
    Anhydrite,
    Apatite,
    Apophyllite,
    Aquamarine,
    Aragonite,
    Argon,
    Asphalt,
    Augelite,
    Axinite,
    Azurite,
    Barite,
    Barytocalcite,
    Benitoite,
    Benzene,
    Beryl,
    Beryllonite,
    Brazilianite,
    BromineLiquid,
    Bronze,
    Brownite,
    Calcite,
    Calspar,
    Cancrinite,
    CarbonDioxideGas,
    CarbonDisulfide,
    CarbonTetrachloride,
    Cassiterite,
    Celestite,
    Cerussite,
    Ceylanite,
    Chalcedony,
    Chalk,
    Chalybite,
    ChlorineGas,
    ChlorineLiquid,
    ChromeGreen,
    ChromeRed,
    ChromeYellow,
    Chromium,
    Chrysoberyl,
    Chrysocolla,
    Chrysoprase,
    Citrine,
    Clinozoisite,
    CobaltBlue,
    CobaltGreen,
    CobaltViolet,
    Colemanite,
    Copper,
    CopperOxide,
    Coral,
    Cordierite,
    Corundum,
    Crocoite,
    Crystal,
    Cuprite,
    Danburite,
    Diamond,
    Diopside,
    Dolomite,
    Dumortierite,
    Ebonite,
    Ekanite,
    Elaeolite,
    Emerald,
    EmeraldSynthFlux,
    EmeraldSynthHydro,
    Enstatite,
    Epidote,
    Ethanol,
    EthylAlcohol,
    Euclase,
    Fabulite,
    FeldsparAdventurine,
    FeldsparAlbite,
    FeldsparAmazonite,
    FeldsparLabradorite,
    FeldsparMicrocline,
    FeldsparOligoclase,
    FeldsparOrthoclase,
    Fluoride,
    Fluorite,
    Formica,
    GarnetAlmandine,
    GarnetAlmandite,
    GarnetAndradite,
    GarnetDemantoid,
    GarnetGrossular,
    GarnetHessonite,
    GarnetRhodolite,
    GarnetSpessartite,
    Gaylussite,
    Glass,
    GlassAlbite,
    GlassCrown,
    GlassCrownZinc,
    GlassFlintDense,
    GlassFlintHeaviest,
    GlassFlintHeavy,
    GlassFlintLanthanum,
    GlassFlintLight,
    GlassFlintMedium,
    Glycerine,
    Gold,
    Hambergite,
    Hauynite,
    Helium,
    Hematite,
    Hemimorphite,
    Hiddenite,
    Howlite,
    HydrogenGas,
    HydrogenLiquid,
    Hypersthene,
    Ice,
    Idocrase,
    IodineCrystal,
    Iolite,
    Iron,
    Ivory,
    JadeNephrite,
    Jadeite,
    Jasper,
    Jet,
    Kornerupine,
    Kunzite,
    Kyanite,
    LapisGem,
    LapisLazuli,
    Lazulite,
    Lead,
    Leucite,
    Magnesite,
    Malachite,
    Meerschaum,
    MercuryLiquid,
    Methanol,
    Moldavite,
    MoonstoneAdularia,
    MoonstoneAlbite,
    Natrolite,
    Nephrite,
    NitrogenGas,
    NitrogenLiquid,
    Nylon,
    Obsidian,
    Olivine,
    Onyx,
    Opal,
    OxygenGas,
    OxygenLiq,
    Painite,
    Pearl,
    Periclase,
    Peridot,
    Peristerite,
    Petalite,
    Phenakite,
    Phosgenite,
    Plastic,
    Plexiglas,
    Polystyrene,
    Prase,
    Prasiolite,
    Prehnite,
    Proustite,
    Purpurite,
    Pyrite,
    Pyrope,
    Quartz,
    QuartzFused,
    Rhodizite,
    Rhodochrisite,
    Rhodonite,
    RockSalt,
    RubberNatural,
    Ruby,
    Rutile,
    Sanidine,
    Sapphire,
    Scapolite,
    ScapoliteYellow,
    Scheelite,
    SeleniumAmorphous,
    Serpentine,
    Shell,
    Silicon,
    Sillimanite,
    Silver,
    Sinhalite,
    Smaragdite,
    Smithsonite,
    Sodalite,
    SodiumChloride,
    Sphalerite,
    Sphene,
    Spinel,
    Spodumene,
    Staurolite,
    Steatite,
    Steel,
    Stichtite,
    StrontiumTitanate,
    Styrofoam,
    Sulphur,
    SyntheticSpinel,
    Taaffeite,
    Tantalite,
    Tanzanite,
    Teflon,
    Thomsonite,
    TigerEye,
    Topaz,
    TopazBlue,
    TopazPink,
    TopazWhite,
    TopazYellow,
    Tourmaline,
    Tremolite,
    Tugtupite,
    Turpentine,
    Turquoise,
    Ulexite,
    Uvarovite,
    Variscite,
    Vivianite,
    Wardite,
    WaterGas,
    Water100DegCelcius,
    Water20DegCelcius,
    Water35DegCelcius,
    Willemite,
    Witherite,
    Wulfenite,
    Zincite,
    ZirconHigh,
    ZirconLow,
    ZirconiaCubic,
};

static inline const std::unordered_map<EMaterialPreset, Real> s_preset_iors {
    { EMaterialPreset::Acetone, 1.36 },
    { EMaterialPreset::Actinolite, 1.618 },
    { EMaterialPreset::Agalmatoite, 1.550 },
    { EMaterialPreset::Agate, 1.544 },
    { EMaterialPreset::AgateMoss, 1.540 },
    { EMaterialPreset::Air, 1.0002926 },
    { EMaterialPreset::Alcohol, 1.329 },
    { EMaterialPreset::Alexandrite, 1.745 },
    { EMaterialPreset::Aluminum, 1.44 },
    { EMaterialPreset::Amber, 1.546 },
    { EMaterialPreset::Amblygonite, 1.611 },
    { EMaterialPreset::Amethyst, 1.544 },
    { EMaterialPreset::Anatase, 2.490 },
    { EMaterialPreset::Andalusite, 1.641 },
    { EMaterialPreset::Anhydrite, 1.571 },
    { EMaterialPreset::Apatite, 1.632 },
    { EMaterialPreset::Apophyllite, 1.536 },
    { EMaterialPreset::Aquamarine, 1.577 },
    { EMaterialPreset::Aragonite, 1.530 },
    { EMaterialPreset::Argon, 1.000281 },
    { EMaterialPreset::Asphalt, 1.635 },
    { EMaterialPreset::Augelite, 1.574 },
    { EMaterialPreset::Axinite, 1.675 },
    { EMaterialPreset::Azurite, 1.730 },
    { EMaterialPreset::Barite, 1.636 },
    { EMaterialPreset::Barytocalcite, 1.684 },
    { EMaterialPreset::Benitoite, 1.757 },
    { EMaterialPreset::Benzene, 1.501 },
    { EMaterialPreset::Beryl, 1.577 },
    { EMaterialPreset::Beryllonite, 1.553 },
    { EMaterialPreset::Brazilianite, 1.603 },
    { EMaterialPreset::BromineLiquid, 1.661 },
    { EMaterialPreset::Bronze, 1.18 },
    { EMaterialPreset::Brownite, 1.567 },
    { EMaterialPreset::Calcite, 1.486 },
    { EMaterialPreset::Calspar, 1.486 },
    { EMaterialPreset::Cancrinite, 1.491 },
    { EMaterialPreset::CarbonDioxideGas, 1.000449 },
    { EMaterialPreset::CarbonDisulfide, 1.628 },
    { EMaterialPreset::CarbonTetrachloride, 1.460 },
    { EMaterialPreset::Cassiterite, 1.997 },
    { EMaterialPreset::Celestite, 1.622 },
    { EMaterialPreset::Cerussite, 1.804 },
    { EMaterialPreset::Ceylanite, 1.770 },
    { EMaterialPreset::Chalcedony, 1.530 },
    { EMaterialPreset::Chalk, 1.510 },
    { EMaterialPreset::Chalybite, 1.630 },
    { EMaterialPreset::ChlorineGas, 1.000768 },
    { EMaterialPreset::ChlorineLiquid, 1.385 },
    { EMaterialPreset::ChromeGreen, 2.4 },
    { EMaterialPreset::ChromeRed, 2.42 },
    { EMaterialPreset::ChromeYellow, 2.31 },
    { EMaterialPreset::Chromium, 2.97 },
    { EMaterialPreset::Chrysoberyl, 1.745 },
    { EMaterialPreset::Chrysocolla, 1.500 },
    { EMaterialPreset::Chrysoprase, 1.534 },
    { EMaterialPreset::Citrine, 1.550 },
    { EMaterialPreset::Clinozoisite, 1.724 },
    { EMaterialPreset::CobaltBlue, 1.74 },
    { EMaterialPreset::CobaltGreen, 1.97 },
    { EMaterialPreset::CobaltViolet, 1.71 },
    { EMaterialPreset::Colemanite, 1.586 },
    { EMaterialPreset::Copper, 1.10 },
    { EMaterialPreset::CopperOxide, 2.705 },
    { EMaterialPreset::Coral, 1.486 },
    { EMaterialPreset::Cordierite, 1.540 },
    { EMaterialPreset::Corundum, 1.766 },
    { EMaterialPreset::Crocoite, 2.310 },
    { EMaterialPreset::Crystal, 2.00 },
    { EMaterialPreset::Cuprite, 2.850 },
    { EMaterialPreset::Danburite, 1.633 },
    { EMaterialPreset::Diamond, 2.417 },
    { EMaterialPreset::Diopside, 1.680 },
    { EMaterialPreset::Dolomite, 1.503 },
    { EMaterialPreset::Dumortierite, 1.686 },
    { EMaterialPreset::Ebonite, 1.66 },
    { EMaterialPreset::Ekanite, 1.600 },
    { EMaterialPreset::Elaeolite, 1.532 },
    { EMaterialPreset::Emerald, 1.576 },
    { EMaterialPreset::EmeraldSynthFlux, 1.561 },
    { EMaterialPreset::EmeraldSynthHydro, 1.568 },
    { EMaterialPreset::Enstatite, 1.663 },
    { EMaterialPreset::Epidote, 1.733 },
    { EMaterialPreset::Ethanol, 1.36 },
    { EMaterialPreset::EthylAlcohol, 1.36 },
    { EMaterialPreset::Euclase, 1.652 },
    { EMaterialPreset::Fabulite, 2.409 },
    { EMaterialPreset::FeldsparAdventurine, 1.532 },
    { EMaterialPreset::FeldsparAlbite, 1.525 },
    { EMaterialPreset::FeldsparAmazonite, 1.525 },
    { EMaterialPreset::FeldsparLabradorite, 1.565 },
    { EMaterialPreset::FeldsparMicrocline, 1.525 },
    { EMaterialPreset::FeldsparOligoclase, 1.539 },
    { EMaterialPreset::FeldsparOrthoclase, 1.525 },
    { EMaterialPreset::Fluoride, 1.56 },
    { EMaterialPreset::Fluorite, 1.434 },
    { EMaterialPreset::Formica, 1.47 },
    { EMaterialPreset::GarnetAlmandine, 1.760 },
    { EMaterialPreset::GarnetAlmandite, 1.790 },
    { EMaterialPreset::GarnetAndradite, 1.820 },
    { EMaterialPreset::GarnetDemantoid, 1.880 },
    { EMaterialPreset::GarnetGrossular, 1.738 },
    { EMaterialPreset::GarnetHessonite, 1.745 },
    { EMaterialPreset::GarnetRhodolite, 1.760 },
    { EMaterialPreset::GarnetSpessartite, 1.810 },
    { EMaterialPreset::Gaylussite, 1.517 },
    { EMaterialPreset::Glass, 1.51714 },
    { EMaterialPreset::GlassAlbite, 1.4890 },
    { EMaterialPreset::GlassCrown, 1.520 },
    { EMaterialPreset::GlassCrownZinc, 1.517 },
    { EMaterialPreset::GlassFlintDense, 1.66 },
    { EMaterialPreset::GlassFlintHeaviest, 1.89 },
    { EMaterialPreset::GlassFlintHeavy, 1.65548 },
    { EMaterialPreset::GlassFlintLanthanum, 1.80 },
    { EMaterialPreset::GlassFlintLight, 1.58038 },
    { EMaterialPreset::GlassFlintMedium, 1.62725 },
    { EMaterialPreset::Glycerine, 1.473 },
    { EMaterialPreset::Gold, 0.47 },
    { EMaterialPreset::Hambergite, 1.559 },
    { EMaterialPreset::Hauynite, 1.502 },
    { EMaterialPreset::Helium, 1.000036 },
    { EMaterialPreset::Hematite, 2.940 },
    { EMaterialPreset::Hemimorphite, 1.614 },
    { EMaterialPreset::Hiddenite, 1.655 },
    { EMaterialPreset::Howlite, 1.586 },
    { EMaterialPreset::HydrogenGas, 1.000140 },
    { EMaterialPreset::HydrogenLiquid, 1.0974 },
    { EMaterialPreset::Hypersthene, 1.670 },
    { EMaterialPreset::Ice, 1.309 },
    { EMaterialPreset::Idocrase, 1.713 },
    { EMaterialPreset::IodineCrystal, 3.34 },
    { EMaterialPreset::Iolite, 1.548 },
    { EMaterialPreset::Iron, 1.51 },
    { EMaterialPreset::Ivory, 1.540 },
    { EMaterialPreset::JadeNephrite, 1.610 },
    { EMaterialPreset::Jadeite, 1.665 },
    { EMaterialPreset::Jasper, 1.540 },
    { EMaterialPreset::Jet, 1.660 },
    { EMaterialPreset::Kornerupine, 1.665 },
    { EMaterialPreset::Kunzite, 1.655 },
    { EMaterialPreset::Kyanite, 1.715 },
    { EMaterialPreset::LapisGem, 1.500 },
    { EMaterialPreset::LapisLazuli, 1.61 },
    { EMaterialPreset::Lazulite, 1.615 },
    { EMaterialPreset::Lead, 2.01 },
    { EMaterialPreset::Leucite, 1.509 },
    { EMaterialPreset::Magnesite, 1.515 },
    { EMaterialPreset::Malachite, 1.655 },
    { EMaterialPreset::Meerschaum, 1.530 },
    { EMaterialPreset::MercuryLiquid, 1.62 },
    { EMaterialPreset::Methanol, 1.329 },
    { EMaterialPreset::Moldavite, 1.500 },
    { EMaterialPreset::MoonstoneAdularia, 1.525 },
    { EMaterialPreset::MoonstoneAlbite, 1.535 },
    { EMaterialPreset::Natrolite, 1.480 },
    { EMaterialPreset::Nephrite, 1.600 },
    { EMaterialPreset::NitrogenGas, 1.000297 },
    { EMaterialPreset::NitrogenLiquid, 1.2053 },
    { EMaterialPreset::Nylon, 1.53 },
    { EMaterialPreset::Obsidian, 1.489 },
    { EMaterialPreset::Olivine, 1.670 },
    { EMaterialPreset::Onyx, 1.486 },
    { EMaterialPreset::Opal, 1.450 },
    { EMaterialPreset::OxygenGas, 1.000276 },
    { EMaterialPreset::OxygenLiq, 1.221 },
    { EMaterialPreset::Painite, 1.787 },
    { EMaterialPreset::Pearl, 1.530 },
    { EMaterialPreset::Periclase, 1.740 },
    { EMaterialPreset::Peridot, 1.654 },
    { EMaterialPreset::Peristerite, 1.525 },
    { EMaterialPreset::Petalite, 1.502 },
    { EMaterialPreset::Phenakite, 1.650 },
    { EMaterialPreset::Phosgenite, 2.117 },
    { EMaterialPreset::Plastic, 1.460 },
    { EMaterialPreset::Plexiglas, 1.50 },
    { EMaterialPreset::Polystyrene, 1.55 },
    { EMaterialPreset::Prase, 1.540 },
    { EMaterialPreset::Prasiolite, 1.540 },
    { EMaterialPreset::Prehnite, 1.610 },
    { EMaterialPreset::Proustite, 2.790 },
    { EMaterialPreset::Purpurite, 1.840 },
    { EMaterialPreset::Pyrite, 1.810 },
    { EMaterialPreset::Pyrope, 1.740 },
    { EMaterialPreset::Quartz, 1.544 },
    { EMaterialPreset::QuartzFused, 1.45843 },
    { EMaterialPreset::Rhodizite, 1.690 },
    { EMaterialPreset::Rhodochrisite, 1.600 },
    { EMaterialPreset::Rhodonite, 1.735 },
    { EMaterialPreset::RockSalt, 1.544 },
    { EMaterialPreset::RubberNatural, 1.5191 },
    { EMaterialPreset::Ruby, 1.760 },
    { EMaterialPreset::Rutile, 2.62 },
    { EMaterialPreset::Sanidine, 1.522 },
    { EMaterialPreset::Sapphire, 1.760 },
    { EMaterialPreset::Scapolite, 1.540 },
    { EMaterialPreset::ScapoliteYellow, 1.555 },
    { EMaterialPreset::Scheelite, 1.920 },
    { EMaterialPreset::SeleniumAmorphous, 2.92 },
    { EMaterialPreset::Serpentine, 1.560 },
    { EMaterialPreset::Shell, 1.530 },
    { EMaterialPreset::Silicon, 4.24 },
    { EMaterialPreset::Sillimanite, 1.658 },
    { EMaterialPreset::Silver, 0.18 },
    { EMaterialPreset::Sinhalite, 1.699 },
    { EMaterialPreset::Smaragdite, 1.608 },
    { EMaterialPreset::Smithsonite, 1.621 },
    { EMaterialPreset::Sodalite, 1.483 },
    { EMaterialPreset::SodiumChloride, 1.544 },
    { EMaterialPreset::Sphalerite, 2.368 },
    { EMaterialPreset::Sphene, 1.885 },
    { EMaterialPreset::Spinel, 1.712 },
    { EMaterialPreset::Spodumene, 1.650 },
    { EMaterialPreset::Staurolite, 1.739 },
    { EMaterialPreset::Steatite, 1.539 },
    { EMaterialPreset::Steel, 2.50 },
    { EMaterialPreset::Stichtite, 1.520 },
    { EMaterialPreset::StrontiumTitanate, 2.410 },
    { EMaterialPreset::Styrofoam, 1.595 },
    { EMaterialPreset::Sulphur, 1.960 },
    { EMaterialPreset::SyntheticSpinel, 1.730 },
    { EMaterialPreset::Taaffeite, 1.720 },
    { EMaterialPreset::Tantalite, 2.240 },
    { EMaterialPreset::Tanzanite, 1.691 },
    { EMaterialPreset::Teflon, 1.35 },
    { EMaterialPreset::Thomsonite, 1.530 },
    { EMaterialPreset::TigerEye, 1.544 },
    { EMaterialPreset::Topaz, 1.620 },
    { EMaterialPreset::TopazBlue, 1.610 },
    { EMaterialPreset::TopazPink, 1.620 },
    { EMaterialPreset::TopazWhite, 1.630 },
    { EMaterialPreset::TopazYellow, 1.620 },
    { EMaterialPreset::Tourmaline, 1.624 },
    { EMaterialPreset::Tremolite, 1.600 },
    { EMaterialPreset::Tugtupite, 1.496 },
    { EMaterialPreset::Turpentine, 1.472 },
    { EMaterialPreset::Turquoise, 1.610 },
    { EMaterialPreset::Ulexite, 1.490 },
    { EMaterialPreset::Uvarovite, 1.870 },
    { EMaterialPreset::Variscite, 1.550 },
    { EMaterialPreset::Vivianite, 1.580 },
    { EMaterialPreset::Wardite, 1.590 },
    { EMaterialPreset::WaterGas, 1.000261 },
    { EMaterialPreset::Water100DegCelcius, 1.31819 },
    { EMaterialPreset::Water20DegCelcius, 1.33335 },
    { EMaterialPreset::Water35DegCelcius, 1.33157 },
    { EMaterialPreset::Willemite, 1.690 },
    { EMaterialPreset::Witherite, 1.532 },
    { EMaterialPreset::Wulfenite, 2.300 },
    { EMaterialPreset::Zincite, 2.010 },
    { EMaterialPreset::ZirconHigh, 1.960 },
    { EMaterialPreset::ZirconLow, 1.800 },
    { EMaterialPreset::ZirconiaCubic, 2.170 },
};

}